site_name: Zentral
theme: readthedocs

repo_url: https://github.com/zentralopensource/zentral
edit_uri: https://github.com/zentralopensource/zentral/edit/main/docs/
docs_dir: docs/
site_dir: build/
extra_css:
- theme/zentral.css

nav:
- Introduction:
  - Welcome to Zentral: index.md
- Configuration:
  - Intro: configuration/index.md
  - API: configuration/api.md
  - Django: configuration/django.md
- Apps:
  - Monolith: apps/monolith.md
- Deployment:
  - Intro: deployment/index.md
  - Docker: deployment/docker-compose.md
  - ZAIO on AWS: deployment/zaio-aws.md
  - ZAIO on GCP: deployment/zaio-gcp.md
  - ZAIO setup: deployment/zaio-setup.md
